baseURL = "https://alviana1412.github.io/"
languageCode = "en-us"
title = "PencariApel"
disablePathToLower = false

#themesDir = "themes"
theme = "jeffprod"


# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
disqusShortname = "alviana1412"



# Number of blog posts in each pagination page
paginate = 6

[permalinks]

# Configures post URLs
 post = "/:year/:filename"

# Make tags and categories work
[indexes]
	tag = "tags"
	category = "categories"

[params]

	# If false, all of blog post will appear on front page (and in pagination)
	truncate = true

	# Search engine URL
	searchEngineURL = "https://www.google.com/search"

	# Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so it was added to index.html manually
	continueReadingText = "Baca selengkapnya..."

	# Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
	googleAnalytics = "UA-XXXXX-X"

  # Switch to true to enable RSS icon link
	rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

	# Website's default description
	defaultDescription = ""

	# Populate this with your own search keywords - these will appear in meta tags
	# defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false
	[taxonomies]
	    tag = "tags"
	    archive = "archives"
